# Generated by Django 4.2.2 on 2023-07-16 17:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsRoom', '0006_alter_news_author_alter_news_publish_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 16, 17, 24, 25, 899951, tzinfo=datetime.timezone.utc)),
        ),
    ]
