# Generated by Django 4.2.2 on 2023-07-18 18:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsRoom', '0008_alter_comments_body_alter_news_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='status',
            field=models.CharField(choices=[('reported', 'Reported'), ('published', 'Published'), ('banned', 'Banned')], default='published', max_length=9),
        ),
        migrations.AlterField(
            model_name='news',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 18, 18, 58, 0, 488458, tzinfo=datetime.timezone.utc)),
        ),
    ]
