# Generated by Django 4.2.2 on 2023-07-20 17:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsRoom', '0011_alter_news_publish_alter_news_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 20, 17, 58, 2, 788038, tzinfo=datetime.timezone.utc)),
        ),
    ]
